Fix metalink generator
QubesOS/qubes-linux-yum pull request #4
Opened 2018-04-16 18:33 UTC by woju

Tested against fedora 25 and 26. Mirrors are from my e-mail archive searched against "mirror" in `Subject:`. Currently not part of repo pipeline, I'd have to figure out how to plug it.

Usage:
```sh
./mkmetalink.py mirrors.list r4.0/current/vm/fc26/repodata/repomd.xml \
    > r4.0/current/vm/fc26/repodata/repomd.xml.metalink
```

This script also supports partial mirrors. Just write subpath to `mirrors.list` after whitespace:
```
https://r40-current.mirror.example/ r4.0/current
```
This is intended for a possibility of optimising out some subparts of the new mirror. We might want to test it before phasing out focaccia with some subset of repos and smaller disk.

QubesOS/qubes-issues#1254

2018-04-16 18:34 UTC, woju commented
@marmarek (I can't assign not request review directly)

2018-04-16 19:06 UTC, marmarek commented
> Mirrors are from my e-mail archive searched against "mirror" in Subject:

https://www.qubes-os.org/downloads/#mirrors

2018-04-16 19:20 UTC, marmarek requested changes

2018-04-16 19:20 UTC, marmarek commented on mkmetalink.py
> +    dest='format',
template

2018-04-16 22:39 UTC, woju commented
I included commented out `.onion`. Also, there is `mirrors.ukfast.co.uk`, which I haven't been able to verify, because it did not resolve (outside UK?), so also commented.

Should we even have a mirror which does not always work? I'd guess it is confusing for people who have to timeout on it.

2018-04-16 22:48 UTC, marmarek commented
> Also, there is mirrors.ukfast.co.uk, which I haven't been able to verify, because it did not resolve (outside UK?), so also commented.

Works for me... Also you have typo there, this is the link: https://mirrors.ukfast.co.uk/sites/qubes-os.org/repo/yum/

> Should we even have a mirror which does not always work? I'd guess it is confusing for people who have to timeout on it.

Yum/dnf automatically fallback to other mirrors, so it shouldn't be a problem.

2018-04-16 23:03 UTC, woju commented
I'm pretty sure it wasn't working 30 min ago, and I clicked the link on qubes-os.org/downloads. But now it works for me too.

2018-04-17 00:47 UTC, marmarek approved these changes

2018-04-17 02:21 UTC, merged